"use client";
import {useParams,useRouter} from "next/navigation";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowUpRight,ArrowDown,Menu,X,Play,Pause,Volume2,Headphones,Mail,ChevronRight} from "lucide-react";

type Lang="en"|"de";
type Credit={id:number;title:string;artist:string;year:string;genre:string;roles:string[];producer:string;image:string;audio?:string;youtube?:string};
const img={
hero:"https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=2200&q=85",
mix:"https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1800&q=85",
mic:"https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1600&q=85",
production:"https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1800&q=85",
film:"https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=85",
team:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1800&q=85",
gear:"https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=1600&q=85"
};
const paths=["","mixing-mastering","production-songwriting","film-scoring","recording","credits","team","booking"];
const dictionary={
en:{nav:["Home","Mixing & Mastering","Production & Songwriting","Film Scoring","Recording","Credits","Studio & Team","Booking"],hero:"YOUR MUSIC.\nOUR PASSION.",tag:"SOUND IS EVERYTHING",sub:"MIXING · MASTERING · PRODUCTION · SONGWRITING · FILM SCORING",discover:"EXPLORE OUR WORK",origin:"A BERLIN STUDIO WITH ROOTS IN 1993",approach:"From the first idea to the final master.",intro:"Every great recording has a story. We help artists find their sound, shape their vision and bring music to life.",services:"WHAT WE DO",selected:"SELECTED WORK",all:"DISCOVER THE CREDITS",team:"THE PEOPLE BEHIND THE SOUND",teamIntro:"Two producers. Distinct perspectives. A shared love of music.",start:"START A PROJECT",cta:"LET'S MAKE SOMETHING GREAT.",creditsIntro:"Explore selected releases by genre, role and producer. Our full archive is being assembled.",noMatch:"No entries match your filters.",sampleNote:"Selected credits are being verified. Imagery is illustrative, not original album artwork.",noAudio:"Audio sample coming soon",bookIntro:"Tell us what you're working on. Together we'll find the right sound.",price:"Rates are provided with your project inquiry, not on service pages.",submit:"PREPARE PROJECT INQUIRY",notice:"Booking requests and online payments are in preparation. This form currently prepares your details locally.",select:"SELECT SERVICE",name:"YOUR NAME",email:"YOUR EMAIL",description:"PROJECT DETAILS",producer:"PRODUCER",genre:"GENRE",role:"ROLE",search:"ARTIST / TITLE",allFilter:"All",tbd:"Profile and selected credits coming soon."},
de:{nav:["Startseite","Mixing & Mastering","Produktion & Songwriting","Filmmusik","Recording","Referenzen","Studio & Team","Booking"],hero:"DEINE LEIDENSCHAFT.\nUNSERE LEIDENSCHAFT.",tag:"KLANG IST ALLES",sub:"MIXING · MASTERING · PRODUKTION · SONGWRITING · FILMMUSIK",discover:"UNSERE ARBEIT ENTDECKEN",origin:"BERLINER STUDIO MIT WURZELN IM JAHR 1993",approach:"Von der ersten Idee bis zum fertigen Master.",intro:"Hinter jeder großartigen Aufnahme steckt eine Geschichte. Wir helfen Künstlern, ihren Sound zu finden und ihre musikalische Vision umzusetzen.",services:"WAS WIR MACHEN",selected:"AUSGEWÄHLTE ARBEITEN",all:"ALLE REFERENZEN ENTDECKEN",team:"DIE MENSCHEN HINTER DEM KLANG",teamIntro:"Zwei Produzenten. Unterschiedliche Perspektiven. Eine gemeinsame Liebe zur Musik.",start:"PROJEKT ANFRAGEN",cta:"LASS UNS ETWAS BESONDERES SCHAFFEN.",creditsIntro:"Entdecke ausgewählte Veröffentlichungen nach Musikrichtung, Tätigkeit und Produzent. Weitere Credits folgen.",noMatch:"Keine passenden Einträge gefunden.",sampleNote:"Die Credits werden geprüft. Die Bilder dienen als Platzhalter und sind keine Originalcover.",noAudio:"Hörprobe folgt",bookIntro:"Erzähl uns von deinem Projekt. Gemeinsam finden wir den richtigen Sound.",price:"Preise erhältst du passend zu deiner Projektanfrage, nicht auf den Leistungsseiten.",submit:"PROJEKTANFRAGE VORBEREITEN",notice:"Direkter Anfrageversand und Onlinezahlungen sind in Vorbereitung. Dieses Formular bereitet deine Angaben zunächst lokal vor.",select:"LEISTUNG AUSWÄHLEN",name:"DEIN NAME",email:"DEINE E-MAIL",description:"PROJEKTBESCHREIBUNG",producer:"PRODUZENT",genre:"GENRE",role:"TÄTIGKEIT",search:"KÜNSTLER / TITEL",allFilter:"Alle",tbd:"Profil und ausgewählte Credits folgen."}
};
const descriptions={
"mixing-mastering":{en:["MIXING & MASTERING","Every detail matters.","Clarity, depth and emotion. We carefully balance every element, giving your track the space and character it deserves."],de:["MIXING & MASTERING","Jedes Detail zählt.","Klarheit, Tiefe und Emotion. Wir geben jedem Element seinen Raum und deinem Song einen unverwechselbaren Charakter."]},
"production-songwriting":{en:["PRODUCTION & SONGWRITING","Ideas become records.","From melody and arrangements to finished productions. We shape each project in close collaboration with the artist."],de:["PRODUKTION & SONGWRITING","Aus Ideen werden Songs.","Von Melodie und Arrangement bis zur fertigen Produktion. Wir gestalten jedes Projekt gemeinsam mit den Künstlern."]},
"film-scoring":{en:["FILM SCORING","Sound tells stories.","Original compositions and musical concepts that support story, pacing and feeling on screen."],de:["FILMMUSIK","Klang erzählt Geschichten.","Originalkompositionen und musikalische Konzepte, die Bild, Dramaturgie und Emotion verbinden."]},
recording:{en:["VOCAL RECORDING & OVERDUBS","Capture the performance.","An intimate, focused environment for vocals and overdubs, where the performance always comes first."],de:["VOCAL RECORDING & OVERDUBS","Den Moment festhalten.","Konzentrierte Vocal-Aufnahmen und Overdubs, bei denen die musikalische Performance an erster Stelle steht."]}
};
const serviceImages=[img.mix,img.production,img.film,img.mic];
const credits:Credit[]=[
{id:1,title:"Leben",artist:"Azad",year:"2001",genre:"Hip-Hop",roles:["Mixing"],producer:"George",image:img.mix},
{id:2,title:"Blue Eyed Soul",artist:"Till Brönner",year:"2002",genre:"Jazz / Soul",roles:["Mixing"],producer:"George",image:img.production},
{id:3,title:"September",artist:"Deborah Cox",year:"1999",genre:"R&B / Soul",roles:["Mixing"],producer:"George",image:img.mic},
{id:4,title:"Haus & Boot",artist:"Kool Savas",year:"2001",genre:"Hip-Hop",roles:["Recording"],producer:"George",image:img.gear}
];
function Photo({src,caption}:{src:string;caption?:string}){return <div className="photobox"><div className="photo" style={{backgroundImage:"url('"+src+"')"}}/>{caption&&<small className="photoCaption">{caption}</small>}</div>}
export default function Page(){
const params=useParams();const router=useRouter();const lang:Lang=params.lang==="de"?"de":"en";const t=dictionary[lang];const raw=params.slug;const slug=Array.isArray(raw)?raw[0]||"":"";const current=paths.includes(slug)?slug:"";const url=(s:string,l:Lang=lang)=>"/"+l+(s?"/"+s:"");
const [menu,setMenu]=useState(false);const [genre,setGenre]=useState("all");const [role,setRole]=useState("all");const [producer,setProducer]=useState("all");const [search,setSearch]=useState("");const [selected,setSelected]=useState<Credit|null>(null);const [isPlaying,setPlaying]=useState(false);const audio=useRef<HTMLAudioElement|null>(null);
useEffect(()=>{setMenu(false);const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("shown");obs.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll(".reveal").forEach(e=>obs.observe(e));return()=>obs.disconnect()},[slug,lang]);
useEffect(()=>{if(!audio.current)return;audio.current.pause();setPlaying(false);if(selected?.audio){audio.current.src=selected.audio;audio.current.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))}},[selected]);
const listed=useMemo(()=>credits.filter(c=>(genre==="all"||c.genre===genre)&&(role==="all"||c.roles.includes(role))&&(producer==="all"||c.producer===producer)&&(c.artist+" "+c.title).toLowerCase().includes(search.toLowerCase())),[genre,role,producer,search]);
const go=(s:string)=>router.push(url(s));
const link=(s:string,label:string,cls="textLink")=><a className={cls} href={url(s)} onClick={e=>{e.preventDefault();go(s)}}>{label}<ArrowUpRight size={18}/></a>;
const [formService,setFormService]=useState("Mixing"),[formProducer,setFormProducer]=useState("No preference"),[formName,setFormName]=useState(""),[formEmail,setFormEmail]=useState(""),[formDetails,setFormDetails]=useState(""),[prepared,setPrepared]=useState(false);
const query=new URLSearchParams({service:formService,producer:formProducer,name:formName,email:formEmail,project:formDetails}).toString();
return <div className="site">
<header className="header"><a className="logo" href={url("")} onClick={e=>{e.preventDefault();go("")}}><strong>AMBER<span>.</span></strong><small>RECORDING STUDIO <b>BERLIN</b></small></a><nav className="nav">{paths.slice(0,7).map((s,i)=><a key={s} className={current===s?"active":""} href={url(s)} onClick={e=>{e.preventDefault();go(s)}}>{t.nav[i]}</a>)}</nav><div className="headerActions"><button className="language" onClick={()=>router.push(url(current,lang==="en"?"de":"en"))}>{lang==="en"?"DE":"EN"}</button>{link("booking",t.nav[7],"headerBook")}<button className="menuButton" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
{menu&&<><button className="menuBackdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/><aside className="mobileMenu" aria-label="Main navigation"><div className="menuInner">{paths.map((p,i)=><a key={p} href={url(p)} className={current===p?"active":""} onClick={e=>{e.preventDefault();setMenu(false);go(p)}}><span>{t.nav[i]}</span><ArrowUpRight size={18}/></a>)}</div></aside></>}
<main key={lang+current}>
{current===""?<><section className="hero" style={{backgroundImage:"linear-gradient(90deg,rgba(5,8,10,.82),rgba(5,8,10,.15)),url('"+img.hero+"')"}}><div className={"heroText reveal shown "+(lang==="de"?"heroTextDE":"")}><small className="warm">{t.tag}</small><h1>{t.hero.split("\n").map((line,i)=><span key={i}>{line}</span>)}</h1><p>{t.sub}</p>{link("credits",t.discover,"textLink light")}</div><div className="scroll"><ArrowDown size={18}/> SCROLL TO EXPLORE</div><span className="pageNumber">01 / 05</span></section>
<section className="intro wrap"><small className="eyebrow warm">{t.origin}</small><div className="columns"><h2 className="reveal">{t.approach}</h2><div className="reveal"><p>{t.intro}</p>{link("team",t.nav[6])}</div></div></section>
<section className="serviceList"><div className="wrap sectionTitle"><small>01 / SERVICES</small><h2>{t.services}</h2></div>{paths.slice(1,5).map((s,i)=><a className="serviceRow reveal" href={url(s)} key={s} onClick={e=>{e.preventDefault();go(s)}}><div className="serviceBg" style={{backgroundImage:"url('"+serviceImages[i]+"')"}}/><div className="serviceCopy"><small>0{i+1} / AMBER</small><h3>{descriptions[s as keyof typeof descriptions][lang][0]}</h3><span className="circleArrow"><ArrowUpRight/></span></div></a>)}</section>
<section className="featured wrap"><div className="sectionTitle"><small>02 / THE WORK</small><h2>{t.selected}</h2></div><div className="featureLayout reveal"><Photo src={img.gear}/><div className="featureText"><small>GEORGE “REDBONE” BRASCH</small><h2>SELECTED EXPERIENCE.</h2><p>Azad · Till Brönner · Kool Savas · Deborah Cox</p>{link("credits",t.all,"outlineLink")}</div></div></section>
<section className="peopleBanner" style={{backgroundImage:"linear-gradient(90deg,rgba(4,8,10,.88),rgba(4,8,10,.2)),url('"+img.team+"')"}}><div className="wrap"><small>03 / TEAM</small><h2>{t.team}</h2><p>{t.teamIntro}</p>{link("team",t.nav[6],"textLink light")}</div></section></>:
Object.prototype.hasOwnProperty.call(descriptions,current)?<><section className="subHero" style={{backgroundImage:"linear-gradient(90deg,rgba(4,8,10,.8),rgba(4,8,10,.15)),url('"+serviceImages[paths.indexOf(current)-1]+"')"}}><div className="wrap"><small>AMBER / SERVICES</small><h1>{descriptions[current as keyof typeof descriptions][lang][0]}</h1><p>{descriptions[current as keyof typeof descriptions][lang][1]}</p></div></section><section className="wrap serviceIntro columns"><div><small className="warm">01 / THE APPROACH</small><h2>{descriptions[current as keyof typeof descriptions][lang][1]}</h2></div><div><p>{descriptions[current as keyof typeof descriptions][lang][2]}</p>{link("booking",t.start,"outlineLink")}</div></section><div className="fullPhoto"><Photo src={img.gear} caption="AMBER / THE DETAILS"/></div><section className="wrap featured"><div className="sectionTitle"><small>02 / EXPERIENCE</small><h2>{t.selected}</h2></div>{link("credits",t.all,"outlineLink")}</section></>:
current==="credits"?<><section className="darkIntro"><div className="wrap"><small>AMBER / DISCOGRAPHY</small><h1>SELECTED <em>CREDITS.</em></h1><p>{t.creditsIntro}</p></div></section><section className="wrap creditSection"><div className="filters"><label>{t.genre}<select value={genre} onChange={e=>setGenre(e.target.value)}><option value="all">{t.allFilter}</option>{Array.from(new Set(credits.map(c=>c.genre))).map(g=><option key={g}>{g}</option>)}</select></label><label>{t.role}<select value={role} onChange={e=>setRole(e.target.value)}><option value="all">{t.allFilter}</option>{["Mixing","Mastering","Recording","Production","Songwriting","Film Scoring"].map(r=><option key={r}>{r}</option>)}</select></label><label>{t.producer}<select value={producer} onChange={e=>setProducer(e.target.value)}><option value="all">{t.allFilter}</option><option>George</option><option>Egor</option></select></label><label>{t.search}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/></label></div><div className="creditGrid">{listed.map(c=><article className="creditItem" key={c.id}><div className="creditArt" style={{backgroundImage:"url('"+c.image+"')"}}><button aria-label={"Open "+c.title+" preview"} onClick={()=>setSelected(c)}><Play/></button></div><div className="creditDetail"><small>{c.year} / {c.genre}</small><h3>{c.title}</h3><p>{c.artist}</p><span>{c.roles.join(", ")} · {c.producer}</span><button onClick={()=>setSelected(c)}>AUDIO <ArrowUpRight size={14}/></button>{c.youtube&&<a href={c.youtube} target="_blank" rel="noopener noreferrer">YOUTUBE <ArrowUpRight size={14}/></a>}</div></article>)}</div>{!listed.length&&<p>{t.noMatch}</p>}<p className="disclaimer">{t.sampleNote}</p></section></>:
current==="team"?<><section className="darkIntro"><div className="wrap"><small>AMBER / PEOPLE</small><h1>STUDIO <em>& TEAM.</em></h1><p>{t.teamIntro}</p></div></section><section className="wrap teamSection"><div className="teamMember"><Photo src={img.mix} caption="GEORGE / BERLIN"/><div><small>PRODUCER / MIXING ENGINEER</small><h2>GEORGE<br/>“REDBONE” BRASCH</h2><p>{lang==="de"?"Gründer des AMBER Recording Studios, das von 1993 bis 2003 in Berlin betrieben wurde. Langjährige Erfahrung in Mixing, Recording, Songwriting und Produktion mit international veröffentlichten Credits.":"Founder of AMBER Recording Studio, originally operating in Berlin from 1993 to 2003. Extensive experience in mixing, recording, songwriting and production, with international credits."}</p><a className="textLink" href="https://www.discogs.com/de/artist/133649-George-Redbone-Brasch" target="_blank" rel="noopener noreferrer">DISCOGS <ArrowUpRight size={18}/></a></div></div><div className="teamMember reversed"><Photo src={img.production} caption="EGOR / BERLIN"/><div><small>PRODUCER</small><h2>EGOR</h2><p>{t.tbd}</p></div></div></section></>:
current==="booking"?<><section className="darkIntro"><div className="wrap"><small>AMBER / BOOKING</small><h1>LET'S WORK <em>TOGETHER.</em></h1><p>{t.bookIntro}</p></div></section><section className="wrap bookingSection"><div className="bookingAside"><small>START YOUR PROJECT</small><h2>{t.cta}</h2><p>{t.price}</p><div className="bookingRule"/><p>BERLIN, GERMANY</p></div><form className="bookingForm" onSubmit={e=>{e.preventDefault();setPrepared(true)}}><label>{t.select}<select value={formService} onChange={e=>setFormService(e.target.value)}>{["Mixing","Mastering","Mixing & Mastering","Music Production","Songwriting","Film Scoring","Vocal Recording / Overdubs"].map(s=><option key={s}>{s}</option>)}</select></label><label>{t.producer}<select value={formProducer} onChange={e=>setFormProducer(e.target.value)}><option>No preference</option><option>George</option><option>Egor</option></select></label><label>{t.name}<input required value={formName} onChange={e=>setFormName(e.target.value)} placeholder="Name"/></label><label>{t.email}<input required type="email" value={formEmail} onChange={e=>setFormEmail(e.target.value)} placeholder="you@example.com"/></label><label className="wideField">{t.description}<textarea required rows={5} value={formDetails} onChange={e=>setFormDetails(e.target.value)} placeholder={lang==="de"?"Genre, Songanzahl, Zeitplan, Wünsche ...":"Genre, tracks, timeline, vision ..."}/></label><p className="formNotice">{t.notice}</p><button type="submit" className="submitButton">{t.submit}<ArrowUpRight size={19}/></button>{prepared&&<div className="formPrepared" role="status"><strong>{lang==="de"?"Deine Projektdaten sind vorbereitet.":"Your project details are prepared."}</strong><p>{lang==="de"?"Der direkte Versand ist noch nicht eingerichtet. Bitte kopiere deine Angaben für die spätere Anfrage.":"Direct delivery is not configured yet. Please copy your details for the future inquiry."}</p><textarea readOnly value={decodeURIComponent(query.replace(/&/g,"\n").replace(/=/g,": "))} rows={5}/></div>}</form></section></>:null}
<section className="bottomCTA"><div className="wrap"><small>AMBER RECORDING STUDIO / BERLIN</small><h2>{t.cta}</h2>{link("booking",t.start,"bottomLink")}</div></section>
</main><footer><div className="wrap footerGrid"><div><strong>AMBER<span>.</span></strong><p>RECORDING STUDIO — BERLIN<br/>EST. 1993</p></div><div>{paths.slice(5).map((s,i)=><a href={url(s)} key={s} onClick={e=>{e.preventDefault();go(s)}}>{t.nav[i+5]}</a>)}</div><div><p>© {new Date().getFullYear()} AMBER RECORDING STUDIO</p><p>BERLIN / DE · EN</p></div></div></footer>
{selected&&<div className="stickyPlayer" role="region" aria-label="Audio player"><div className="playerThumb" style={{backgroundImage:"url('"+selected.image+"')"}}/><div className="playerTitle"><strong>{selected.title}</strong><span>{selected.artist}</span></div>{selected.audio?<button onClick={()=>{if(isPlaying){audio.current?.pause();setPlaying(false)}else{audio.current?.play().then(()=>setPlaying(true))}}}>{isPlaying?<Pause/>:<Play/>}</button>:<span className="audioPending">{t.noAudio}</span>}<button className="playerClose" onClick={()=>setSelected(null)} aria-label="Close"><X size={19}/></button><audio ref={audio} onEnded={()=>setPlaying(false)}/></div>}
</div>;
}
